messages:
  manualDiscord:                            #Сообщение при вызове на проверку через Discord (/ss check onDiscord)
    - ""
    - "        §4ПРОВЕРКА       "
    - "    Anti-Cheat System    "
    - " "
    - "◉ Для завершения проверки"
    - "вам необходимо предоставить ваш Discord."
    - " "
    - "◉ У вас есть 3 минуты, чтобы отправить его в чат."
    - " "
    - "◉ Пример:"
    - "└── ✦ Discord: SuperSteve#1234"
    - " "
    - "⚠ ВАЖНО:"
    - "▸ Убедитесь, что вы написали свой никнейм и тег точно."
    - " "
    - "➜ Ожидаем ваш ответ..."
  manualonAnyDesk:                             #Сообщение при вызове на проверку через AnyDesk (/ss check onAnyDesk)
    - ""
    - "        §4ПРОВЕРКА       "
    - "    Anti-Cheat System    "
    - " "
    - "◉ Для завершения проверки"
    - "вам необходимо предоставить ваш AnyDesk."
    - " "
    - "◉ У вас есть 3 минуты, чтобы отправить его в чат."
    - " "
    - "◉ Пример:"
    - "└── ✦ AnyDesk: 463 345 932"
    - " "
    - "⚠ ВАЖНО:"
    - "▸ Убедитесь, что вы написали свой ID точно."
    - " "
    - "➜ Ожидаем ваш ответ..."
  verification-completed:                       #Сообщение при успешной проверке (/ss check yes)
    - ""
    - "    §aПРОВЕРКА НА ЧИТЫ ПРОЙДЕНА      "
    - "        §7РЕЗУЛЬТАТ: §aЧИСТЫЙ          "
    - ""
    - "✔ ВАШ АККАУНТ УСПЕШНО ПРОШЕЛ ПРОВЕРКУ"
    - ""
    - "◉ Статус:"
    - "└── ✦ Читы: Не обнаружены"
    - ""
    - "◉ Ограничения сняты."
    - "Вы свободны и можете продолжать игру."
    - ""
    - "Приятной игры на сервере!"
    - ""
    - "➜ Все системы разблокированы"
target-player: "§cИгрок не найден или не в сети!" #Сообщение если администратор пытается вызвать игрока не в сети
freezing: "§4Вы заморозили игрока: {player}" #Сообщение которое отправляется администратору при выполнении команды /ss check onDiscord | onAnydesk
unfreezing: "§aВы разморозили игрока: {player}" #То же сообщение для администратора
send-title: "§4ПРОВЕРКА" #Сообщение на экране
send-title-next: "§7Смотрите в чат!" #Нижнее предложение под словом ПРОВЕРКА
permissions-reload: "§4У вас нет прав на использование этой команды!" #Сообщение если у игрока нет Permissions
on-my-own: "§cВы не можете использовать эту команду на самом себе" #Сообщение когда админ пытается вызвать себя на проверку
on-verification: "§4Игрок уже на проверке" #Сообщение если админ пытается вызвать игрока уже на проверке
off-verification: "§aИгрок не на проверке" #Сообщение если админ пытается завершить проверку игроку который не на проверке
error-use-command: "§4Использование: /at <reload | check> <on | off | yes | no> [игрок]" #Сообщение об ошибке
ban-admin-messages: "§aВы заблокировали игрока: {player}" #Сообщение для администратора о блокировке игрока
chat-admin-use: "§cИспользуйте: /admintoolchat <сообщение>"
chat-format: "§6[AdminChat] §b%player%§f: %message%" #Формат чата Администрации (то как он будет выглядеть)
ban-reason: "По результатам проверки"
title-settings:
  appearance: 10 #Время появления текста в тиках 20 тиков = 1 сек Стандарт: 10
  show: 100 #Время показа текста на экране в тиках 20 тиков = 1 сек Стандарт: 100
  disappearance: 20 #Время исчезновения текста в тиках 20 тиков = 1 сек Стандарт: 20
sound-settings:
  type-sound: Sound.ENTITY_EXPERIENCE_ORB_PICKUP
  volume: 1
  height: 1