name: AdminToolkit
version: '1.0.1'
main: _4iz.AdminToolkit.Main
api-version: '1.21'
load: STARTUP
authors: [ _4iz ]
commands:

  admintoolkit:
    description: Команда для проверки игрока на стороннее ПО
    usage: Использование /<command> <reload | check> <on | off | yes | no> [игрок]
    aliases:
      - at
      - admintool
    permission: admintoolkit.use
    permission-message: У вас нет прав на использовании этой команды!
  admintoolchat:
    description: Команда для проверки игрока на стороннее ПО
    usage: Использование /<command> сообщение
    aliases:
      - ac
      - achat
    permission: admintoolchat.use
    permission-message: У вас нет прав на использовании этой команды!
permissions:
  admintoolkit.use:
    description: Позволяет использовать команду /admintoolkit
    default: op
  admintoolkit.reload:
    description: Позволяет использовать команду /admintoolkit reload
    default: op
  admintoolchat.use:
    description: Позволяет использовать команду /admintoolchat reload
    default: op